language: python

python:
    - "3.4"

install: 
    - sudo apt-get install scons
    - pip install typing st pycodestyle

script:
    - scons
    - pycodestyle . --max-line-length=120
    - python -m pytest

notifications:
    email: false
