language: python

python:
    - "3.4"

install: 
    - pip install typing st pycodestyle

script:
    - sudo apt-get install scons
    - scons -uj4
    - pycodestyle . --max-line-length=120

notifications:
    email: false
