language: python
python:
- '3.4'
install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
- sudo apt-get install g++-4.9
- sudo apt-get install scons
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
script:
- scons
- pycodestyle . --max-line-length=120
- python -m pytest
before_deploy: scons
deploy:
  provider: pypi
  user: Jefung
  skip_cleanup: true
  on:
    all_branches: true
notifications:
  email: false
env:
  global:
    secure: oevznC3IapwHNClbZ3q1zPgNuZkDKIZGPYh6jAPtynRmVuj56JZC7GojSj96sd7QmgwOZuzdmZ28nwOR63oyb2KZx4GEnJ8P5NBqQKYJN3Wb/CpSQNfzbqhUA/9iOvSilUhr/TENJMlTrIywZfuQPT9Nnhobjv1IljVIdCcJ2oEHjqFhWwhsBwS6xnWrsPEGF9FR7GEJNf4Kofi4eKUeRDKdogddoxnZqAvDazjtdd3sfWSlJn+PpSSnxOAKgdwHGfeDSC6dYAULFPB5zws/R560ApWVsZerjF7wK7DrCtvAMBsJZ/9WGJD6fE2GiJyMHf77JCOt8GOhtFoKTARdDdO+FiGT5spubUy3dUV69pQCrq6D9V8e57Fyydu3F9EIeIdtIBiNxsXW1queP2cvpYg/Me4rcVPVPqPbShSfM2tvoP8JDTTe1Y3cRtcM52V3/AXhX/3DYhkaY4l8w7GocrXlou46VscRuun6o6dVeb8r2gI56rguGM2duEp2gbzeLekzZ1M+RLeyRPvDRx8lMG9IEgihPEL4c97YW5xYIiAexokOpuQg+owWMZwADH8RyZcWHmRUONVBbz6L1A9WN6AipO8NGKeEVWs2I2xYjNhHJTNHbZQ1IaNVZup8k9+KQO7jvsnupcNNQqOJp9uFr7amiOc3PMagECSx3H6BBCE=
