environment:
  PYTHON: "C:\\Python36"

install:
  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install -U pip wheel setuptools
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install scons

before_test:
  - python --version
  - scons --version

build_script:
  - python -m scons -j%NUMBER_OF_PROCESSORS% MSVC_VERSION=11.0

test_script:
  - pycodestyle . --max-line-length=120
  - python -m pytest
